Broadcast
Udyam/ees23-backend pull request #3
Opened 2022-12-24 19:13 UTC by archit-2003

2022-12-29 14:05 UTC, Ankur-Agrawal-ece20 requested changes

2022-12-29 18:33 UTC, Samar1110 commented on customauth/views.py
> +
added serializer

2022-12-30 10:52 UTC, Samar1110 reviewed
Done All changes

2023-01-15 09:24 UTC, Ankur-Agrawal-ece20 commented on customauth/views.py
> +
It should be outside InputSerializer

2023-01-15 09:27 UTC, Ankur-Agrawal-ece20 requested changes
Update inputserializer part

2023-01-27 11:18 UTC, merged